version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - "noah-janzen"
    labels:
      - Dependencies
    commit-message:
      prefix: chore
