name: Get next version

on: pull_request

jobs:
  get-next-version:
    name: Get next version
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Output files
      run: ls
    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@main
    - name: Show the next version
      run: |
        echo ${{ steps.get_next_version.outputs.version }}
        echo ${{ steps.get_next_version.outputs.hasNextVersion }}
