name: QA

on: pull_request

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: install Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod
    - name: Run tests
      run: go test ./...

