name: QA

on: pull_request

jobs:
  qa:
    name: QA
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod
    - name: Run tests
      run: go test ./...
